### ISSUE TITLE
Preserve files properties.

### ISSUE THREAD

**Issue by Ackar** [kevva/decompress#18]
Since commit 090849b1f9ef2f152c79349e244010f1b0091214 ("New pluggable API") the properties of extracted files are no more preserved, this include the `mode`, `uid`, `mtime` and I think links (basically most of the information contained in the inode).

This will most certainly breaks all modules relying on this to compile binaries, i.e. all modules using `bin-builder` if it ever gets updated to use the latest version of this module. For example trying to execute `./configure` will fail since the file no more has the exec permission.

**Comment by grebett** [comment]
Sorry to reopen this issue but it seems you have fixed only the mode bug. Extracting files, especially symlinks as I noticed, are still losing their properties. Am I wrong?
