### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by frankrousseau** [kevva/decompress#19]
Hello there,

First, thank you for your building such a useful module. 

Here is my problem. When I try to run decompress it is asking for 'is-absolute' module. Is that normal?

**Comment by kevva** [comment]
Probably some nested dependency that didn't get installed. Try installing this again and have another go.

**Comment by frankrousseau** [comment]
Yep, don't know why I had to clean the `node_modules` folder. Then, it worked. Sorry for that issue and thank you for your help.
