### ISSUE TITLE
Incorrectly decompressing through multiple streams

### ISSUE THREAD

**Issue by rylnd** [kevva/decompress#20]
When attempting to extract a tar.gz archive of [WordPress](https://github.com/WordPress/WordPress), Decompress correctly used Decompress.targz to extract everything, but then continued to pass those files through the other decompression plugins. Eventually, it encountered a [.xap file](https://github.com/WordPress/WordPress/blob/master/wp-includes/js/plupload/plupload.silverlight.xap), which it attempted to unzip, resulting in an error due to the files being Windows files.

Obviously this is not the desired behavior. I can see addressing this in a few ways:

1. Decompress.zip should not attempt to decompress .xap files. Perhaps `isZip()` should return false, or there should be some other short circuit here. While it technically _is_ a zip file, it is not meant to be decompressed; I'm sure there are a lot of file extensions that fall into this category. Maybe there should be a blacklist for these types of extensions?

2. Some better handling of the decompression plugins. Perhaps you could `use` the decompression plugins based on extension, or skip the remaining plugins once the first succeeds? I realize that this is not a issue that's going to be hit often: for example, changing the order of these plugins would also fix my problem (but that's definitely not a long-term solution). 

If this 'multiple decompressions' behavior is desired, I would either make that an option that has to be enabled, or at least document that behavior explicitly. 

FYI I originally hit this while using yeoman/generator's [extract](https://github.com/yeoman/generator/blob/master/lib/actions/fetch.js#L48) function.

**Comment by kevva** [comment]
1. I agree that `is-zip` should return `false` on `.xap` files. It's checking the magic numbers of the file and apparently that file matches the `.zip` numbers, which is weird.

2. Checking the extension is not as safe as checking the magic numbers of a file. And setting it inside `decompress` or the plugins wouldn't make a difference.

Ultimately, this is an issue with `is-zip` for falsy detection of `.zip` files.

**Comment by rylnd** [comment]
Thanks for the response. Would you like me to open this issue over there, then?

Just to clarify, your opinion is that the decompress-multiple-times behavior is intentional and should be the default?

**Comment by kevva** [comment]
@rylnd, ah, I see your point. No, I don't think it should decompress files inside an already decompress file. I'll have a look at it.

**Comment by rylnd** [comment]
Thanks @kevva!
