### ISSUE TITLE
Support .xz format

### ISSUE THREAD

**Issue by piranna** [kevva/decompress#22]
As pointed at https://github.com/kevva/download/issues/55, .xz format being used as standard by GNU packages is not supported, There are several libraries can be used:

https://www.npmjs.com/package/xz
https://www.npmjs.com/package/node-liblzma
https://www.npmjs.com/package/lzma-native

Also some of them in pure Javascript:

https://github.com/cscott/lzma-purejs
https://github.com/nmrugg/LZMA-JS

**Comment by kevva** [comment]
Is it just the `xz` format or is it used in conjunction with `tar`?

**Comment by piranna** [comment]
.tar.xz, the same way as .tar-gz.

**Comment by kevva** [comment]
https://github.com/kevva/decompress-tarxz. The pure JS alternatives didn't work so I went with `lzma-native`.

**Comment by piranna** [comment]
Great, thank you. Seems I need to include it manually, isn't it?

**Comment by kevva** [comment]
Yes, since this needs some native bindings I'm not going to include it by default.

**Comment by piranna** [comment]
Ok, good idea.

**Comment by dsherret** [comment]
I wanted a non-native solution, so this worked for my purposes (somewhat patterned off https://github.com/kevva/decompress-tarxz/blob/master/index.js but didn't handle every scenario because I just needed something hacky for a script):

```ts
import decompress from "decompress";
import xzDecompress from "xz-decompress";
import * as fileType from "file-type";
import decompressTar from "decompress-tar";
import { Buffer } from "node:buffer";

const files = await decompress(filePath, outputDir, {
      plugins: [async (input) => {
        const isBuffer = Buffer.isBuffer(input);
	const type = isBuffer ? await fileType.fileTypeFromBuffer(input) : undefined;
        if (!type || type.ext !== 'xz') {
          return [];
        }

        const stream = new ReadableStream({
          start(controller) {
            controller.enqueue(input);
            controller.close();
          },
        });
        const decompressor = new xzDecompress.XzReadableStream(stream);
        const finalBuffer = Buffer.concat(await Array.fromAsync(decompressor));
        const result = decompressTar()(finalBuffer);
        return result;
      }],
    });
```
