### ISSUE TITLE
New version for commit "Bump `vinyl-fs` dependency"?

### ISSUE THREAD

**Issue by Aldream** [kevva/decompress#23]
Hey!
Great job with this module! Just one thing:

I run into an error when installing _decompress_, because of the vinyl-fs dependency. I saw you corrected  the problem (commit fb43c2fc0fb1e87bd0b3c16ccab02f0c6fedd017), but I don't think the change as been repercuted to the last version for npm (ie. the last version 2.2.1 doesn't take this commit into account, seemingly making it impossible to install it through npm). Am I wrong?

**Comment by kevva** [comment]
Fixed. Try installing `2.3.0`.

**Comment by Aldream** [comment]
Perfect! That was quick, thanks!
