### ISSUE TITLE
Version backwards compatibility 

### ISSUE THREAD

**Issue by NicholasABriganti** [kevva/decompress#27]
I have a project that uses dependencies that leverage decompress. I noticed that yesterday you upgraded to version 3.0.0 and my builds have begun breaking. I do not use decompress directly, however it looks like many of my direct dependencies reference it. I noticed that your repository only has 1 branch and when I try to download version 2.3.0 (most previous version) manually I am unable to do so. I believe that this is causing all of my other dependencies to break during my build.

I was just wondering if you had any insight into this issue?

**Comment by kevva** [comment]
Need more info to determine what's happening here. Can you give any error output or something?

**Comment by jmcunningham** [comment]
We are having this same problem where I work. Our builds are broken due to this update. I believe one (actually, more than 1) of dependencies in our package.json file has a sub-dependency on decompress. The error we are seeing is:
```
npm ERR! git clone git@github.com:github:kevva/decompress Cloning into bare repository '/var/lib/jenkins/.npm/_git-remotes/git-github-com-github-kevva-decompress-521c46aa'...
npm ERR! git clone git@github.com:github:kevva/decompress fatal: remote error: 
npm ERR! git clone git@github.com:github:kevva/decompress    is not a valid repository name
npm ERR! git clone git@github.com:github:kevva/decompress   Email support@github.com for help
npm ERR! notarget No compatible version found: decompress@'github:kevva/decompress#d1f881352b48b9f04318a046dc5033e6fae7a233'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.2.5","0.1.10","0.1.5","0.2.4","0.3.3","0.1.6","0.2.5","0.1.3","0.2.2","0.3.1","0.1.4","0.2.3","0.3.2","0.1.9","0.1.7","0.1.8","0.1.1","0.2.0","0.1.2","0.2.1","0.3.0","0.1.0","3.0.0","2.0.0","2.1.0","2.1.1","2.2.0","2.1.2","2.2.1","2.3.0","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7","1.0.0","0.1.10","1.0.1","1.0.2"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by shinnn** [comment]
> npm ERR! notarget No compatible version found: decompress@'github:kevva/decompress#d1f881352b48b9f04318a046dc5033e6fae7a233'

Interesting. I can download it with

```
npm i decompress@'github:kevva/decompress#d1f881352b48b9f04318a046dc5033e6fae7a233'
```

and the commit d1f881352b48b9f04318a046dc5033e6fae7a23 actually exists.

@NicholasABriganti @jmcunningham Node and npm version?

Anyway I unpublished [download](https://github.com/kevva/download) v4.3.1 and v4.4.0 since they have [a problem](https://github.com/kevva/download/issues/81).
