### ISSUE TITLE
Files are not extracted and no error is thrown.

### ISSUE THREAD

**Issue by Bartozzz** [kevva/decompress#28]
When I am trying to unzip a file, the callback is executed but there's no extracted files in the destination directory and no error is thrown. The file to unzip exists (checked in Finder and with `console.log ( fs.existsSync( file ) );`.

**Environment**

Decompress version: 3.0.0
Node.js version : v0.12.0

I am working on OS X El Capitan.

**Code:**

    var Decompress = require( "decompress" );

    var file = "/Users/Username/Desktop/App/node_cache/0.12.0/package.zip";
    var dest = "/Users/Username/Desktop/App/node_cache/0.12.0/";

    new Decompress()
        .src( file )
        .dest( dest )
        .use( Decompress.zip( { stripe: 1 } )
        .run( function ( error ) {
            if ( error ) {
                console.log( error );
            } else {
                console.log( "ok" );
            }
        } );

**Comment by dfberry** [comment]
Same operating system as above.

I get this too. But I get in when I run from dirA. When I run from dirB, it returns the files. Both A and B are inside parent C. The entire code base and zip file run for A and B is the same, the only difference I can tell is the parent directory. I've stepped through the code in the debugger looking for the issue where the list of file names is erased but I can't find it. If I knew where that was, I could compare the debug sessions between the two different code bases. 

Or is there a way to capture errors or print to console?

**Comment by sysrage** [comment]
Also using OSX but running Node 4.2.1. Trying to extract a self-extracting zip and seeing similar behavior as reported above. After running, the destination directory contains nothing but the self-extracting zip (which wasn't in that directory before using decompress).

**Comment by m69** [comment]
OSX Yosemite and node.js 4.2.2 and having the issue. Zip file is being copied to directory that decompress creates without being extracted. Tried decompress and the stand alone zip plugin, no dice.

**Comment by DustinCampbell** [comment]
I've got the same issue but I'm only seeing it on Windows. Sometimes it works and sometimes it doesn't. Is there a race somewhere?

**Comment by juliangruber** [comment]
same issue on osx and node 5.4.1

**Comment by DustinCampbell** [comment]
I've seen it on OS X now as well.

**Comment by kevva** [comment]
Could you guys try `4.0.0` and see if it still happens?

**Comment by juliangruber** [comment]
it's working now with a .tbz i created myself, but not finding any files in a .tbz downloaded of the internet. i'll open an issue on the plugin repo

**Comment by Bartozzz** [comment]
It is now working for me as well.
