### ISSUE TITLE
Can we change plugins to peerDependencies?

### ISSUE THREAD

**Issue by petrbrzek** [kevva/decompress#32]
For example I only use tarGz in my project and I'm not interested in zip, etc.

**Comment by shinnn** [comment]
In this case you can use [`vinyl-fs`](https://github.com/gulpjs/vinyl-fs) and [`decompress-targz`](https://github.com/kevva/decompress-targz) directly. See the second example of https://github.com/kevva/decompress-targz#usage.

There is room for dependency size reduction of this package, but at least we won't use `peerDependencies`. In my experience `peerDependencies` would rather cause a lot of problems
than bring benefit.

Thanks for the suggestion, @petrbrzek.

**Comment by shinnn** [comment]
@petrbrzek Are you currently using `decompress` directly, or as one of the dependencies of [`download`](https://github.com/kevva/download)?

**Comment by petrbrzek** [comment]
We are using it directly in Avocode but I really like the  `download` package so we'll probably use it instead of bloated `request` package.

**Comment by shinnn** [comment]
I found [`tar-fs`](https://github.com/mafintosh/tar-fs) (+ [`gunzip-maybe`](https://github.com/mafintosh/gunzip-maybe) for .gz support) which really meets your requirements I guess.
