### ISSUE TITLE
Node <4 support with babel

### ISSUE THREAD

**Issue by pofider** [kevva/decompress#40]
Would you consider using babel to support older versions of node.js using babel transpilation?

I'm offering help with PR on this, if you like.

In every case, thank you for this lib, it is the only one which works correctly with XLSX files for me.

**Comment by SamVerschueren** [comment]
Why do you want to support older versions?

**Comment by pofider** [comment]
I don't know the exact statistics, but I guess that more than 50% of current installations are using node <4. 

My project [jsreport](http://jsreport.net) would like to depend on this library, and in my case there is no need to force users to upgrade node.js except this particular lib.

I can easily fork this... I just wanted to know if you(or maintainers) would considering supporting older versions.

**Comment by kevva** [comment]
No, I won't introduce a compilation step to support versions below `4.x.x`.
