### ISSUE TITLE
Filter directories instead of files

### ISSUE THREAD

**Issue by Bartozzz** [kevva/decompress#43]
I wonder if there is a way to filter directories instead of files within the `option.filter` function. Does `decompress` provides a way to do it or I have to delete them after decompressing, in a promise?

I am trying to delete all the `*.lproj` (this is actually a directory, not a file) from an OS X application:

```javascript
const LOCALES = /example\.app\/Contents\/Resources\/(.*?)\.lproj/;

decompress( fullPath, cache, {
    strip  : 1,
    filter : file => {
        return path.extname( file.path ) !== ".html"
            && ! LOCALES.test( file.path );
    }
} ).then( files => {
    // Delete the package once it's decompressed
    fs.unlinkSync( fullPath );

    resolve();
} );
```

**Comment by kevva** [comment]
You should be able to do it, the `filter` option will iterate through all files, including directories.

**Comment by kevva** [comment]
You can check if a file is a directory by checking `file.type === 'directory'`.
