### ISSUE TITLE
Decouple builtin plugins?

### ISSUE THREAD

**Issue by tunnckoCore** [kevva/decompress#44]
Currently i just uses `decompress-unzip`, but it needs some more workarounds it because of the `dest`. I don't need the others. Yea they are pretty small deps, but... would be better. :)

**Comment by shinnn** [comment]
FYI you can directly use a plugin without `decompress`. Example: https://github.com/shinnn/get-zonetab/blob/ddf68e876dcc93cc891d3c289c45f97ea215d3ad/index.js#L15

**Comment by tunnckoCore** [comment]
Yea, that's what I'm doing now, but i should handle files manually.

```js
utils.unzip()(buf).then((files) => {
 // handle / decompress files
})
```

**Comment by shinnn** [comment]
[maxogden/extract-zip](https://github.com/maxogden/extract-zip) seems to fit your use case.
