### ISSUE TITLE
Unsupport Chinese Character

### ISSUE THREAD

**Issue by Comee** [kevva/decompress#47]
The zip file structure is:
===
![image](https://cloud.githubusercontent.com/assets/5416227/21168591/34aa08ba-c1f0-11e6-9774-46d7a85b42c4.png)

After decompress, the structure is:
===
![image](https://cloud.githubusercontent.com/assets/5416227/21168597/46bf9f06-c1f0-11e6-89f5-875ab26bd8b8.png)

Note: file name is not correct.
===

**Comment by sindresorhus** [comment]
Can you submit a [failing test](https://github.com/avajs/ava#failing-tests)?

**Comment by yozosann** [comment]
@Comee  How to resolve it finally ？

**Comment by Comee** [comment]
You can fix it before you write it to disk

[index.js](https://github.com/kevva/decompress/blob/master/index.js)

![image](https://user-images.githubusercontent.com/5416227/45739846-786d2c80-bc26-11e8-90bc-b5da699b2356.png)

**Comment by yozosann** [comment]
I write a function to convert garble path to chinese.
You can try it in your needed place.
`
decompress(path.join(__dirname, './七夕的副本.zip'), './中奖名单').then(files => {
    files.forEach(file => console.log(garbleToChinese(file.path)));
});

function garbleToChinese(garble) {
    if(typeof(garble) !== 'string') throw new Error('Not a string');
    var cp437 = '\u0000☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←∟↔▲▼ !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~⌂ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ¢£¥₧ƒáíóúñÑªº¿⌐¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ ';
    var rs = garble.split('').reduce((pre, cur) => {
        pre.push(cp437.split('').findIndex(v => v === cur));
        return pre;
    }, []);
    return new Buffer(rs).toString('utf-8');
}
`
get result:
`
七夕的副本/
七夕的副本/.DS_Store
__MACOSX/
__MACOSX/七夕的副本/
__MACOSX/七夕的副本/._.DS_Store
七夕的副本/1.png
__MACOSX/七夕的副本/._1.png
七夕的副本/收集卡 /
七夕的副本/收集卡 /.DS_Store
`

**Comment by yozosann** [comment]
`七夕的副本/
七夕的副本/.DS_Store
__MACOSX/
__MACOSX/七夕的副本/
__MACOSX/七夕的副本/._.DS_Store
七夕的副本/1.png
__MACOSX/七夕的副本/._1.png
七夕的副本/收集卡 /
七夕的副本/收集卡 /.DS_Store`

**Comment by wizardpisces** [comment]
@yozosann you saved my day

**Comment by hopepdm** [comment]
@yozosann In this way, only the correct characters can be output on the console. In fact, the extracted file name on the server is still garbled

**Comment by meteorlxy** [comment]
```ts
import iconvLite from 'iconv-lite';

decompress(foo, {
  map(file) {
    return {
      ...file,
      path: iconvLite.encode(file.path, 'cp437').toString(),
    };
  },
})
```
