### ISSUE TITLE
Pre-POSIX.1-1988 (i.e. v7) tar

### ISSUE THREAD

**Issue by Xflofoxx** [kevva/decompress#49]
Hi,
I have an issue while opening an old tar.bz file, it seems that the problem is that the https://github.com/sindresorhus/file-type library cannot recognize the "tar" format becouse it is pre-posix.1-1988 version and there is no "magic number" for such files. You can follow the issue I opened with that library here:
- https://github.com/sindresorhus/file-type/issues/76

However, if I bypass the file check in the plugin decompress-tar the tarStream seems to extract correctly the files. I think that adding a new option called "legacyTar" is a good compromise.

I'm going to add a pool request soon, for the module and also for the following plugins:
- https://github.com/kevva/decompress-tar
- https://github.com/kevva/decompress-tarbz2

Thanks

**Comment by kevva** [comment]
Closing in favor of the issue in `file-type` that you referenced.
