### ISSUE TITLE
Does the `decompress-bzip2` plugin need updating to the new plugin syntax?

### ISSUE THREAD

**Issue by josephrocca** [kevva/decompress#53]
In the `decompress-bzip2` repo the example code is like this:

```javascript
var decompress = new Decompress().src('foo.jpg.bz2').dest('dest').use(bzip2());
decompress.run(function (err, files) {
    if (err) { throw err; }
    console.log('Files extracted successfully!'); 
});
```

However, the main repo (this one) seems to suggest that the syntax should be like this:

```javascript
decompress('unicorn.bz2', 'dist', {
  plugins: [decompressBz2()]
}).then(files => {
  console.log('done!');
});
// or presumably:
let files = await decompress('unicorn.bz2', 'dist', { plugins: [decompressBz2()] });
```
Is the bz2 plugin outdated? I noticed that it hasn't been edited in 2 years, whereas the others were updated 11 months ago. Cheers :)

**Comment by kevva** [comment]
I've updated it now, although it has one drawback. When extracting files from it, you don't get the filename so you have to provide that one yourself. See the [docs](https://github.com/kevva/decompress-bzip2#usage) for more information.
