### ISSUE TITLE
Error: `Uncaught (in promise) Error: absolute path: /`

### ISSUE THREAD

**Issue by GoldFrite** [kevva/decompress#90]
Hello,
When I try to unzip a ZIP file of about 175 MB, I get the following error: `Uncaught (in promise) Error: absolute path: /`.
But when I try to unzip a smaller file (about 50 MB), there is no problem.
Can you help me?
Thanks.

**Comment by ePjet** [comment]
Hi, have you closed this issue because you found a fix? if yes i'd be interested as the same error occurs.
